import { ProductCategory, ProductUnit } from '@models/product';

export const mockProductsList = [
    {
        "price": 2.36,
        "name": "Aix BIO",
        "isSliceable": "true",
        "unit": ProductUnit.UNIT,
        "category": ProductCategory.PIECE,
        "description": "T110, lin, pavot, millet, tournesol, avoine, courge",
        "shortDelivery": false,
        "available": true,
        "productId": "yALoE6TDM5yVwJBS5Qmv"
    },
    {
        "description": "",
        "category": ProductCategory.MIE,
        "isSliceable": "true",
        "unit": ProductUnit.UNIT,
        "name": "Bagel",
        "shortDelivery": false,
        "available": true,
        "price": 0.8,
        "productId": "1qmxQyywcZobJsfHQfVM"
    },
    {
        "name": "Baguette Aunis BIO",
        "description": "T110",
        "unit": ProductUnit.UNIT,
        "isSliceable": "true",
        "shortDelivery": false,
        "available": true,
        "price": 1.42,
        "category": ProductCategory.BAGUETTE,
        "productId": "MaQHcrsrTAnisN6hvQZL"
    },
    {
        "name": "Baguette M",
        "category": ProductCategory.BAGUETTE,
        "isSliceable": "true",
        "available": true,
        "price": 1.04,
        "description": "tradition, T65",
        "shortDelivery": true,
        "unit": ProductUnit.UNIT,
        "productId": "vPZBpBvqn4EsQefndoH9"
    },
    {
        "available": true,
        "description": "T110, graines de sésame torréfiées",
        "isSliceable": "true",
        "unit": ProductUnit.UNIT,
        "shortDelivery": true,
        "price": 1.04,
        "category": ProductCategory.BAGUETTE,
        "name": "Baguette Rochelaise BIO",
        "productId": "Lcr6aDapzVGv0fhmqEmi"
    },
    {
        "shortDelivery": false,
        "price": 1.04,
        "name": "Baguette Épeautre BIO",
        "isSliceable": "true",
        "description": "Grand épeautre",
        "category": ProductCategory.BAGUETTE,
        "available": true,
        "unit": ProductUnit.UNIT,
        "productId": "3XW9nYNNPuaWc6q4uQcj"
    },
    {
        "category": ProductCategory.VIENNOISERIE,
        "unit": ProductUnit.UNIT,
        "isSliceable": "true",
        "available": false,
        "name": "Boule au sucre",
        "shortDelivery": false,
        "price": 0.76,
        "description": "Brioche nature",
        "productId": "DGUI0Mm8WNQViEMQ07fr"
    },
    {
        "category": ProductCategory.VIENNOISERIE,
        "price": 18.9,
        "available": true,
        "name": "Brioche 10 personnes",
        "isSliceable": "true",
        "shortDelivery": false,
        "description": "Brioche nature",
        "unit": ProductUnit.UNIT,
        "productId": "aSGHPU2HlUXrx6ggwxv0"
    },
    {
        "unit": ProductUnit.UNIT,
        "shortDelivery": false,
        "price": 23.63,
        "isSliceable": "true",
        "category": ProductCategory.VIENNOISERIE,
        "name": "Brioche 10 personnes chocamande",
        "description": "Brioche pépites de chocolat, amandes",
        "available": true,
        "productId": "14jD1LmZPlCik094FmeG"
    },
    {
        "price": 23.63,
        "unit": ProductUnit.UNIT,
        "description": "Brioche à la pistache, éclats de pistaches torréfiées",
        "available": true,
        "name": "Brioche 10 personnes pistache",
        "isSliceable": "true",
        "shortDelivery": false,
        "category": ProductCategory.VIENNOISERIE,
        "productId": "Q0thPeyKLFkEHc3LT2Vc"
    },
    {
        "unit": ProductUnit.UNIT,
        "name": "Brioche Bernier",
        "description": "Brioche nature",
        "available": true,
        "isSliceable": "true",
        "price": 3.31,
        "shortDelivery": true,
        "category": ProductCategory.VIENNOISERIE,
        "productId": "kmKYUHpLUSkshzAtXSgU"
    },
    {
        "description": "Tarte au sucre",
        "available": true,
        "unit": ProductUnit.UNIT,
        "isSliceable": "true",
        "name": "Brioche bressane",
        "shortDelivery": true,
        "category": ProductCategory.VIENNOISERIE,
        "price": 1.04,
        "productId": "UNJDxwzGAHufBKgAdjDe"
    },
    {
        "name": "Brioche chocamande",
        "price": 5.2,
        "shortDelivery": true,
        "isSliceable": "true",
        "available": true,
        "unit": ProductUnit.UNIT,
        "category": ProductCategory.VIENNOISERIE,
        "description": "Brioche aux pépites de chocolat, amandes",
        "productId": "A3jfSh2Y7StCUBwGON1P"
    },
    {
        "available": true,
        "description": "",
        "unit": ProductUnit.UNIT,
        "price": 1.04,
        "category": ProductCategory.VIENNOISERIE,
        "isSliceable": "true",
        "name": "Brioche feuilletée individuelle",
        "shortDelivery": true,
        "productId": "NsJmQOmDeyE0u5B1PzXd"
    },
    {
        "shortDelivery": true,
        "available": true,
        "name": "Brioche pistache",
        "price": 5.2,
        "description": "Brioche à la pistache, éclats de pistaches torréfiées",
        "category": ProductCategory.VIENNOISERIE,
        "unit": ProductUnit.UNIT,
        "isSliceable": "true",
        "productId": "Sb1jN5Gr9mHUDItBcgI4"
    },
    {
        "description": "Chocolats, Noix",
        "price": 1.04,
        "unit": ProductUnit.UNIT,
        "name": "Brownies",
        "available": true,
        "shortDelivery": true,
        "isSliceable": "true",
        "category": ProductCategory.GATEAU,
        "productId": "NGNf9vSgGH0oHZ0sBgSs"
    },
    {
        "category": ProductCategory.MIE,
        "name": "Buns",
        "shortDelivery": false,
        "available": true,
        "description": "Pain burger",
        "unit": ProductUnit.UNIT,
        "isSliceable": "true",
        "price": 0.8,
        "productId": "Now465Xyfs1L8s2iiFlO"
    },
    {
        "shortDelivery": true,
        "available": true,
        "price": 1.42,
        "description": "",
        "category": ProductCategory.VIENNOISERIE,
        "unit": ProductUnit.UNIT,
        "isSliceable": "true",
        "name": "Cagouille pralines",
        "productId": "2MTFdzF4qY8rLemVRDq0"
    },
    {
        "shortDelivery": true,
        "price": 1.42,
        "description": "Pain aux raisins",
        "category": ProductCategory.VIENNOISERIE,
        "available": true,
        "unit": ProductUnit.UNIT,
        "name": "Cagouille raisins",
        "isSliceable": "true",
        "productId": "BkNndHweiyXSbLckc1Br"
    },
    {
        "name": "Cake citron pavot",
        "category": ProductCategory.GATEAU,
        "description": "Prix au centimètre",
        "unit": ProductUnit.UNIT,
        "shortDelivery": true,
        "isSliceable": "true",
        "available": true,
        "price": 0.57,
        "productId": "EfK8EKQdnsKMbsx4N17G"
    },
    {
        "shortDelivery": true,
        "available": true,
        "price": 0.57,
        "description": "Prix au centimètre",
        "isSliceable": "true",
        "unit": ProductUnit.UNIT,
        "name": "Cake marbré chocolat",
        "category": ProductCategory.GATEAU,
        "productId": "cEnL4MNmzDfHwKjWh8DU"
    },
    {
        "unit": ProductUnit.UNIT,
        "price": 0.57,
        "available": true,
        "shortDelivery": true,
        "isSliceable": "true",
        "category": ProductCategory.GATEAU,
        "name": "Cake orange chocolat",
        "description": "Prix au centimètre",
        "productId": "3L76Tuln8KFeTi6f79aq"
    },
    {
        "shortDelivery": false,
        "name": "Charentaise aux pommes",
        "available": true,
        "isSliceable": "true",
        "description": "Chausson aux pommes",
        "category": ProductCategory.GATEAU,
        "unit": ProductUnit.UNIT,
        "price": 1.42,
        "productId": "rpeCEAjZG0ddfOpWvUHm"
    },
    {
        "description": "Pain italien à l'huile d'olive",
        "shortDelivery": false,
        "isSliceable": "true",
        "unit": ProductUnit.KG,
        "price": 5.67,
        "name": "Chiabatta",
        "available": true,
        "category": ProductCategory.COUPE,
        "productId": "NZY8Xl5N06gAPY5CWOBs"
    },
    {
        "shortDelivery": true,
        "price": 1.04,
        "category": ProductCategory.VIENNOISERIE,
        "unit": ProductUnit.UNIT,
        "available": true,
        "isSliceable": "true",
        "description": "",
        "name": "Chocolatine",
        "productId": "qvcLf97piZ19nHBAeXIT"
    },
    {
        "description": "Petit épeautre, cranberries, noix de pécan",
        "category": ProductCategory.GATEAU,
        "available": true,
        "name": "Cookie américain",
        "isSliceable": "true",
        "shortDelivery": true,
        "unit": ProductUnit.UNIT,
        "price": 1.04,
        "productId": "fxmDzsl6S9XdVwwDHUHQ"
    },
    {
        "shortDelivery": true,
        "available": true,
        "name": "Cookie classique",
        "description": "",
        "isSliceable": "true",
        "category": ProductCategory.GATEAU,
        "unit": ProductUnit.UNIT,
        "price": 1.04,
        "productId": "VmkODvWQVAucXXNFyg8L"
    },
    {
        "available": true,
        "category": ProductCategory.VIENNOISERIE,
        "price": 1.04,
        description: "",
        "isSliceable": "true",
        "unit": ProductUnit.UNIT,
        "name": "Croissant",
        "shortDelivery": true,
        "productId": "DE14MUgULzywFQ7hFB2E"
    },
    {
        "price": 18.9,
        "unit": ProductUnit.KG,
        "shortDelivery": false,
        "available": true,
        "isSliceable": "true",
        "category": ProductCategory.GATEAU,
        "name": "Croissant aux amandes revisité",
        "description": "",
        "productId": "gPC13yj842p79xKuXSx2"
    },
    {
        "available": true,
        "category": ProductCategory.GATEAU,
        "shortDelivery": true,
        "isSliceable": "true",
        "unit": ProductUnit.UNIT,
        "price": 5.1,
        "name": "Diamants (sachet de 9)",
        "description": "3 café, 3 vanille, 3 chocolat",
        "productId": "eGGR3y4YXMQBoWfgqCUK"
    },
    {
        "price": 14.18,
        "available": true,
        "shortDelivery": false,
        "name": "Engrain BIO",
        "isSliceable": "true",
        "unit": ProductUnit.KG,
        "description": "Petit épeautre intégral",
        "category": ProductCategory.COUPE,
        "productId": "fehaL8E6ndhidiY7T81f"
    },
    {
        "name": "Epeautre d'automne",
        "available": true,
        "category": ProductCategory.COUPE,
        "unit": ProductUnit.KG,
        "shortDelivery": false,
        "description": "Grand épeautre, fruits secs, noisettes, pistaches",
        "price": 9.45,
        "isSliceable": "true",
        "productId": "upH1lle4CJke4NKdH1U4"
    },
    {
        "unit": ProductUnit.UNIT,
        "available": false,
        "price": 10,
        "shortDelivery": false,
        "name": "Galette des rois 4 personnes",
        "isSliceable": "true",
        "category": ProductCategory.VIENNOISERIE,
        "description": "",
        "productId": "mbgpRS8qxI0aRD6Zdid9"
    },
    {
        "price": 15.17,
        "description": "",
        "available": false,
        "name": "Galette des rois 6 personnes",
        "category": ProductCategory.VIENNOISERIE,
        "unit": ProductUnit.UNIT,
        "isSliceable": "true",
        "shortDelivery": false,
        "productId": "8NIdUW68Dsjg0rAjiMI8"
    },
    {
        "price": 20.85,
        "available": false,
        "description": "",
        "category": ProductCategory.VIENNOISERIE,
        "shortDelivery": false,
        "unit": ProductUnit.UNIT,
        "isSliceable": "true",
        "name": "Galette des rois 8 personnes",
        "productId": "GS4z0TEUqBfouS6NyHpY"
    },
    {
        "name": "Grand pain de mie",
        "price": 5.67,
        "available": true,
        "shortDelivery": false,
        "description": "",
        "isSliceable": "true",
        "category": ProductCategory.MIE,
        "unit": ProductUnit.UNIT,
        "productId": "fX5jQrMbhgWJDUPJBa80"
    },
    {
        "name": "Grand épeautre BIO",
        "category": ProductCategory.COUPE,
        "description": "Grand épeautre",
        "unit": ProductUnit.KG,
        "isSliceable": "true",
        "available": true,
        "shortDelivery": false,
        "price": 6.62,
        "productId": "tzoqwS44Zcfgu6LeSxSL"
    },
    {
        "available": true,
        "unit": ProductUnit.UNIT,
        "description": "",
        "shortDelivery": true,
        "isSliceable": "true",
        "name": "Grande brioche feuilletée",
        "category": ProductCategory.VIENNOISERIE,
        "price": 4.25,
        "productId": "GtKPkZQPLi75jda1aK2I"
    },
    {
        "description": "T110",
        "category": ProductCategory.INDIVIDUEL,
        "shortDelivery": false,
        "name": "Individuel Aunis BIO",
        "isSliceable": "true",
        "price": 0.47,
        "unit": ProductUnit.UNIT,
        "available": true,
        "productId": "CijqlbyseUU3hWbXQvut"
    },
    {
        "category": ProductCategory.INDIVIDUEL,
        "available": true,
        "description": "tradition, T65",
        "isSliceable": "true",
        "name": "Individuel M",
        "price": 0.43,
        "unit": ProductUnit.UNIT,
        "shortDelivery": false,
        "productId": "14ZtNzPEjbMmVbD7pYkr"
    },
    {
        "shortDelivery": false,
        "name": "Individuel Rochelais BIO",
        "available": true,
        "isSliceable": "true",
        "price": 0.43,
        "category": ProductCategory.INDIVIDUEL,
        "unit": ProductUnit.UNIT,
        "description": "T110, graines de sésame torréfiées",
        "productId": "pR3bYTD1G84KWDHPdOoq"
    },
    {
        "description": "Grand épeautre",
        "category": ProductCategory.INDIVIDUEL,
        "available": true,
        "name": "Individuel Épeautre BIO",
        "shortDelivery": true,
        "isSliceable": "true",
        "unit": ProductUnit.UNIT,
        "price": 0.43,
        "productId": "NOnRoOVnN6BM2acNi20H"
    },
    {
        "isSliceable": "true",
        "price": 14.18,
        "name": "Marathonien",
        "available": true,
        "unit": ProductUnit.KG,
        "shortDelivery": false,
        "description": "Fruits macérés à la vanille bourbon, noisettes, miel",
        "category": ProductCategory.COUPE,
        "productId": "Pw7demJwP2AjcGWkORy1"
    },
    {
        "name": "Mini brioche bressane",
        "available": true,
        "isSliceable": "true",
        "category": ProductCategory.VIENNOISERIE,
        "description": "",
        "price": 0.47,
        "unit": ProductUnit.UNIT,
        "shortDelivery": false,
        "productId": "vGxR9Da9SofzKMrPh3A9"
    },
    {
        "category": ProductCategory.VIENNOISERIE,
        "price": 0.52,
        "description": "Brioche aux pépites de chocolat, amandes",
        "available": true,
        "name": "Mini brioche chocamande",
        "isSliceable": "true",
        "unit": ProductUnit.UNIT,
        "shortDelivery": false,
        "productId": "U2YlrxaiS6Ioj7YkrQAn"
    },
    {
        "category": ProductCategory.VIENNOISERIE,
        "available": true,
        "price": 0.52,
        "name": "Mini brioche pistache",
        "isSliceable": "true",
        "shortDelivery": false,
        "description": "Brioche à la pistache, éclats de pistaches torréfiées",
        "unit": ProductUnit.UNIT,
        "productId": "uHvOXyWG3YC0mMm5t4gW"
    },
    {
        "name": "Mini buns",
        "shortDelivery": false,
        "category": ProductCategory.MIE,
        "description": "Mini pain burger",
        "isSliceable": "true",
        "available": true,
        "price": 0.38,
        "unit": ProductUnit.UNIT,
        "productId": "rYYM8ouQIMbMmJibgVYY"
    },
    {
        "unit": ProductUnit.UNIT,
        "category": ProductCategory.VIENNOISERIE,
        "available": true,
        "isSliceable": "true",
        "description": "Mini viennoiserie aux pralines",
        "shortDelivery": false,
        "name": "Mini cagouille pralines",
        "price": 0.71,
        "productId": "kERcnqPSKvBQRdVRjOQj"
    },
    {
        "description": "Mini pain aux raisins",
        "price": 0.71,
        "shortDelivery": false,
        "name": "Mini cagouille raisins",
        "isSliceable": "true",
        "available": true,
        "category": ProductCategory.VIENNOISERIE,
        "unit": ProductUnit.UNIT,
        "productId": "JuwZWIVvf2kgbac35JvU"
    },
    {
        "category": ProductCategory.VIENNOISERIE,
        "name": "Mini chocolatine",
        "isSliceable": "true",
        "available": true,
        "description": "",
        "shortDelivery": false,
        "unit": ProductUnit.UNIT,
        "price": 0.47,
        "productId": "0SLckoQlKXXvxD3bQWpn"
    },
    {
        "price": 0.47,
        "available": true,
        "category": ProductCategory.VIENNOISERIE,
        "shortDelivery": false,
        "isSliceable": "true",
        "name": "Mini croissant",
        "unit": ProductUnit.UNIT,
        "description": "",
        "productId": "xWrZ9SdCeqOPIsidIT03"
    },
    {
        "description": "",
        "available": true,
        "category": ProductCategory.VIENNOISERIE,
        "shortDelivery": false,
        "isSliceable": "true",
        "price": 0.76,
        "name": "Mini pain au cacao",
        "unit": ProductUnit.UNIT,
        "productId": "GeiZwAD1Fh42dbnWFx05"
    },
    {
        "available": true,
        "description": "T110",
        "shortDelivery": false,
        "unit": ProductUnit.KG,
        "category": ProductCategory.COUPE,
        "isSliceable": "true",
        "name": "Oléronnais BIO",
        "price": 8.98,
        "productId": "I2WRbOUyuLoCQAU4SFMP"
    },
    {
        "name": "Pain apéro",
        "isSliceable": "true",
        "description": "Lardons, emmental ",
        "category": ProductCategory.PIECE,
        "shortDelivery": true,
        "unit": ProductUnit.UNIT,
        "price": 1.42,
        "available": true,
        "productId": "SkVyvNTTsfwMYFWebPVn"
    },
    {
        "unit": ProductUnit.UNIT,
        "category": ProductCategory.PIECE,
        "price": 1.42,
        "shortDelivery": true,
        "available": true,
        "name": "Pain au cacao",
        "isSliceable": "true",
        "description": "Cacao, pistoles de chocolat",
        "productId": "YG3CXJvIccAZngXTp9fW"
    },
    {
        "description": "",
        "unit": ProductUnit.KG,
        "available": true,
        "shortDelivery": true,
        "price": 18.9,
        "isSliceable": "true",
        "name": "Pain d'épices",
        "category": ProductCategory.GATEAU,
        "productId": "lff19Jx8VQY6JAu5Sbmd"
    },
    {
        "description": "Cube de pain de mie, 16 centimètres d'arête",
        "available": true,
        "name": "Pain de mie au kilo",
        "shortDelivery": false,
        "isSliceable": "true",
        "price": 9.45,
        "category": ProductCategory.MIE,
        "unit": ProductUnit.KG,
        "productId": "9j2FnKLLNEh99xDW7R7C"
    },
    {
        "description": "",
        "shortDelivery": true,
        "category": ProductCategory.GATEAU,
        "unit": ProductUnit.UNIT,
        "name": "Palmier",
        "price": 1.04,
        "isSliceable": "true",
        "available": true,
        "productId": "YUGOVt7oCLUhm1KD0bJf"
    },
    {
        "isSliceable": "true",
        "name": "Pavé M",
        "category": ProductCategory.PIECE,
        "description": "tradition, T65",
        "available": true,
        "price": 1.42,
        "unit": ProductUnit.UNIT,
        "shortDelivery": true,
        "productId": "lMNasb9cMFWf4VAhDcCW"
    },
    {
        "category": ProductCategory.MIE,
        "unit": ProductUnit.UNIT,
        "name": "Petit pain de mie",
        "isSliceable": "true",
        "price": 3.31,
        "shortDelivery": false,
        "description": "",
        "available": true,
        "productId": "Dpq4ErXGczcEXNGVYmrK"
    },
    {
        "price": 3.78,
        "category": ProductCategory.PATES,
        "shortDelivery": false,
        "isSliceable": "true",
        "available": true,
        "unit": ProductUnit.UNIT,
        "description": "Cercle de 30 centimètres de diamètre",
        "name": "Pâte feuilletée",
        "productId": "sSqyNwMZLyfAoC6WjoLH"
    },
    {
        "shortDelivery": false,
        "available": true,
        "category": ProductCategory.PATES,
        "unit": ProductUnit.UNIT,
        "isSliceable": "true",
        "name": "Pâte feuilletée 60X40",
        "description": "Plaque 60X40 centimètres",
        "price": 14.18,
        "productId": "vbDaxNXMB4IUFJOHhfEn"
    },
    {
        "unit": ProductUnit.UNIT,
        "name": "Pâte sablée",
        "available": true,
        "category": ProductCategory.PATES,
        "isSliceable": "true",
        "price": 14.18,
        "description": "",
        "shortDelivery": false,
        "productId": "GRyvACMOFcateN4TVCxu"
    },
    {
        "unit": ProductUnit.UNIT,
        "shortDelivery": false,
        "description": "",
        "price": 9.45,
        "available": true,
        "isSliceable": "true",
        "name": "Pâte à brioche",
        "category": ProductCategory.PATES,
        "productId": "6PbqM113J4Q1oufDJtyr"
    },
    {
        "name": "Pâte à croissant",
        "available": true,
        "price": 1.04,
        "description": "Croissants crus à faire pousser et cuire soi même",
        "unit": ProductUnit.UNIT,
        "isSliceable": "true",
        "shortDelivery": false,
        "category": ProductCategory.PATES,
        "productId": "tiXsLD4WygpiWHjjGlPO"
    },
    {
        "available": true,
        "shortDelivery": true,
        "category": ProductCategory.PATES,
        "price": 1.04,
        "name": "Pâte à pizza",
        "isSliceable": "true",
        "unit": ProductUnit.UNIT,
        "description": "",
        "productId": "fy7no0y5diNEZ2i8OBUE"
    },
    {
        "unit": ProductUnit.KG,
        "description": "T 110, graines de sésame torréfiées",
        "isSliceable": "true",
        "available": true,
        "category": ProductCategory.COUPE,
        "shortDelivery": false,
        "name": "Rochelais BIO",
        "price": 5.67,
        "productId": "H8yyrnqLENgxxXbil5F2"
    },
    {
        "shortDelivery": false,
        "description": "Blé & Seigle",
        "isSliceable": "true",
        "available": true,
        "price": 9.45,
        "category": ProductCategory.COUPE,
        "name": "Rétais BIO",
        "unit": ProductUnit.KG,
        "productId": "PdPmyqZ8KdUFs4TA8xtC"
    },
    {
        "shortDelivery": false,
        "isSliceable": "true",
        "unit": ProductUnit.UNIT,
        "category": ProductCategory.PIECE,
        "price": 3.78,
        "available": true,
        "name": "Saintongeais BIO",
        "description": "Pain complet, intégral",
        "productId": "C4b9xpgpw1qdDogJDpQg"
    },
    {
        "shortDelivery": false,
        "available": true,
        "unit": ProductUnit.UNIT,
        "price": 0.76,
        "isSliceable": "true",
        "name": "Sandwich Aunis BIO",
        "description": "T110",
        "category": ProductCategory.SANDWICH,
        "productId": "ysWwRowUmK1XvrhYOgYp"
    },
    {
        "shortDelivery": false,
        "description": "tradition, T65",
        "name": "Sandwich M",
        "category": ProductCategory.SANDWICH,
        "price": 0.76,
        "unit": ProductUnit.UNIT,
        "isSliceable": "true",
        "available": true,
        "productId": "7ZIddEP65PshWuDUxJt3"
    },
    {
        "unit": ProductUnit.UNIT,
        "shortDelivery": false,
        "description": "T110, graines de sésame torréfiées",
        "price": 0.76,
        "category": ProductCategory.SANDWICH,
        "isSliceable": "true",
        "name": "Sandwich Rochelaise BIO",
        "available": true,
        "productId": "UB6gfT8Psem9SVmMpLy9"
    },
    {
        "unit": ProductUnit.UNIT,
        "category": ProductCategory.SANDWICH,
        "shortDelivery": false,
        "available": true,
        "price": 0.76,
        "isSliceable": "true",
        "description": "Grand épeautre",
        "name": "Sandwich Épeautre BIO",
        "productId": "w466Ljzqst7rueTVcLMx"
    },
    {
        "name": "Sans Gluten BIO",
        "price": 14.18,
        "category": ProductCategory.COUPE,
        "shortDelivery": false,
        "isSliceable": "true",
        "unit": ProductUnit.KG,
        "available": true,
        "description": "Riz, sarrasin, châtaigne",
        "productId": "IzPVTuYmCdwDb4vjLKPq"
    },
    {
        "description": "Seigle, T170",
        "isSliceable": "true",
        "category": ProductCategory.PIECE,
        "price": 4.25,
        "available": true,
        "unit": ProductUnit.UNIT,
        "shortDelivery": false,
        "name": "Seigle auvergnat BIO",
        "productId": "5JmRS3AGcdAQGc44D4SY"
    },
    {
        "description": "Seigle, cranberries",
        "available": true,
        "unit": ProductUnit.KG,
        "category": ProductCategory.COUPE,
        "shortDelivery": false,
        "name": "Seigle aux cranberries BIO",
        "price": 14.18,
        "isSliceable": "true",
        "productId": "4iOUlvlBsd2Wcvo2DYi5"
    }
]